drop table if exists book;
DROP TABLE IF EXISTS person;

CREATE TABLE person
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    FIO              VARCHAR                           NOT NULL,
    date_of_birth    date not null
);

create table book
(
    id        integer generated by default as identity primary key,
    person_id INTEGER NOT NULL,
    FOREIGN KEY (person_id) REFERENCES person(id),
    title     varchar,
    author    varchar,
    year      integer
);